### ISSUE TITLE
Rotation not working

### ISSUE THREAD

**Issue by d3t4** [Rabalaba/NerdPack-Rabbs#2]
It seems that only druid rotations are working....while looking through codes of other classes there was rabbs1="number", what does it mean???

**Comment by Rabalaba** [comment]
you need to download my ovale addon as well

**Comment by d3t4** [comment]
still not working can u tell me what modules is needed for it to work except nerdpack and nerdpack protected.. thanks in advance

**Comment by d3t4** [comment]
nevermind got it working !!! thanks for the rotation 👍
